### ISSUE TITLE
Don't Know How To Build It

### ISSUE THREAD

**Issue by balloman** [CapdinCrando/The-Rainbow-Mod#1]
How do I build this all that is there is the source files.

**Comment by CapdinCrando** [comment]
Here are the steps to installing forge with Intellij:

1. Make sure you have the latest Java SDK
2. Download Minecraft Forge Reccommended Source for 1.7.10: http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html
3. Extract folder to destination
4. Open build.grade, and add this to the end of the file(without quotes): "idea { module { inheritOutputDirs = true } }"
5. Shift + right click on "forge" folder, click "Open command prompt here"
6. Run this in command prompt: "gradlew setupDecompWorkspace --refresh-dependencies"
7. Import Intellij project from Forge Folder
8. Open the Gradle Sidebar
9. Under "Tasks" double click "setupDecompWorkspace", then double click "genIntellijRuns"
10. Replace "forge/src" with Rainbow Mod src

**Comment by balloman** [comment]
Shouldn't this be in the Readme?
